In [7]:
import numpy as np
import time

In [8]:
arr=np.array([1,2,3,4,5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [9]:
#execution performance
size=10_00_000

#python list
py_list=list(range(size))
start=time.time()

sq_list=[x**2 for x in py_list]
end=time.time()

print(f"python list time={end-start} seconds")


#numpy array
np_array=np.array(py_list)
start=time.time()
sq_list=np_array**2
end=time.time()

print(f"numpy array time={end-start} seconds")

python list time=0.14848875999450684 seconds
numpy array time=0.025406599044799805 seconds


In [10]:
#memory
import sys

print(f"python list size={sys.getsizeof(py_list) * len(py_list)} bytes")


print(f"numpy list size={np_array.nbytes} bytes")

python list size=8000056000000 bytes
numpy list size=8000000 bytes


In [16]:
#creating np array
arr=np.array([1,2,3,4,5])

print(arr, type(arr), arr.dtype, arr.shape)

arr2=np.array([1,2,3,4,"simran"])

print(arr2, type(arr2), arr2.dtype, arr2.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' 'simran'] <class 'numpy.ndarray'> <U21 (5,)


In [20]:
#creating 2D array using numpy
arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr2D, arr2D.shape, arr2D.dtype)


[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3) int64


In [45]:
#creating numpy array using in-built methods
arr=np.zeros((3,3), dtype="int64")
print(arr)                           #prefill with 0 values

arr2=np.ones((5,6), dtype="int64")
print(arr2)                         #prefill with 1 values

arr3=np.full((2,2), 100, dtype="int64")
print(arr3)                         #prefill with 100 now

arr4=np.eye(3, dtype="int64")
print(arr4)                        #this matrix basically creates the matrix with diagonal value 1 and we pass square matrix

arr5=np.arange(0,11, 2)
print(arr5)                       #it sets the values in range

arr6=np.linspace(1, 100, 3)
print(arr6)                       #evenly spaced array

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
[[100 100]
 [100 100]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[ 0  2  4  6  8 10]
[  1.   50.5 100. ]


In [48]:
#Properties
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr.shape)                  #matrix= rows and columns
print(arr.dtype)                  #type
print(arr.size)                  #total size
print(arr.ndim)                  #which dimension array is this

#type casting
float_arr=arr.astype(np.float64)
print(float_arr, type(float_arr), float_arr.dtype)

(3, 3)
int64
9
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] <class 'numpy.ndarray'> float64


In [63]:
#operations on array
arr=np.array([[1,2,3],[4,5,6]])
print(arr, arr.shape)

#reshaping
reshaped_arr=arr.reshape((3,2))
print(reshaped_arr, reshaped_arr.shape)


#flattened array: means convery into 1D array
flattened_arr=arr.flatten()
print(flattened_arr, flattened_arr.shape)


#Indexing
arr=np.array([1,2,3,4,5,6])             #1D array

print(arr[1])
print(arr[5])

arr2D=np.array([[1,2,3],[4,5,6]])

print(arr2D[1][1])
print(arr2D[1][2])


#Fancy Indexing: to access multiple values at one time
arr=np.array([1,2,3,4,5,6])     
idx=[1,3,5]                 #give indexes
print(arr[idx])


#boolean indexing: returns on the true values
arr=np.array([1,2,3,4,5,6])  

print(arr[arr>2])
print(arr[arr!=2])


#slicing
arr=np.array([1,2,3,4,5,6])  

print(arr[2:])
print(arr[::2])

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)
2
6
5
6
[2 4 6]
[3 4 5 6]
[1 3 4 5 6]
[3 4 5 6]
[1 3 5]


In [68]:
#copy: python list vs view: numpy array(original)
list1=[1,2,3,4,5,6]
copy=list1[1:3]
copy[0]=200
print(copy)
print(list1)

arr=np.array([1,2,3,4,5,6])  
view=arr[1:3]
view[0]=200
print(view)
print(arr)

#create copy in numpy array
arr=np.array([1,2,3,4,5,6])  
view=arr[1:4].copy()

view[1]=300
print(view)

print(arr)

[200, 3]
[1, 2, 3, 4, 5, 6]
[200   3]
[  1 200   3   4   5   6]
[  2 300   4]
[1 2 3 4 5 6]


In [72]:
#data types
#downcast: change higher data type to lower data type

#complex datatype
arr=np.array([3+4j])
arr2=np.array([4+7j])

print(arr+arr2)

#object datatype
arr=np.array(["prime",{1,2,4},3.14])
print(arr, arr.dtype)

[7.+11.j]
['prime' {1, 2, 4} 3.14] object


In [81]:
#Multi-dimensional arrays
arr=np.array([1,2,3,4,5,6])
print(np.sum(arr))


sum_of_column=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.sum(sum_of_column, axis=0))

sum_of_rows=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.sum(sum_of_rows, axis=1))


#slicing in 2D array
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0:2, 1:2])

21
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [91]:
#3-Dimensional array
arr3D=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])

print(arr3D, arr3D.shape)

#indexing
print(arr3D[0, 1,1])

#slicing
print(arr3D[:,0,:])                   #first row from both layers

#first columns from both layers
print(arr3D[:,:,0])

#manuplating 3-Dimensional array
arr3D[:,:,0]=99

print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]
[[[99  2]
  [99  4]
  [99  6]]

 [[99  8]
  [99 10]
  [99 12]]]


In [95]:
#vectorization
arr=np.array([1,2,3,4,5,6,7])
arr2=np.array([8,9,10,11,12,13,14])

print(arr**2)
print(arr+arr2)

[ 1  4  9 16 25 36 49]
[ 9 11 13 15 17 19 21]


In [104]:
#broadcasting: works where there is difference in the size of(means wher one array is of size 1) numpy arrays
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([7,8,9,10,11,12])

print(arr1+arr2)


#but 
arr1=np.array([[1,2,3,4,5,6],[8,9,2,1,7,9]])
arr2=np.array([[7,8,9,10,11,12],[5,7,9,2,1,9],[8,7,0,4,7,5]])

print(arr1.shape)
print(arr2.shape)

#print(arr1+arr2)             #this will return beacuse broadcast is possible only where one of the array has size=1

[ 8 10 12 14 16 18]
(2, 6)
(3, 6)


In [106]:
#normalize
arr=np.array([[1,2,3,4,5,6],[8,9,2,1,7,9]])

mean=np.mean(arr)
std_dev=np.std(arr)

normalized_arr=(arr-mean)/std_dev
print(normalized_arr)

print(mean)
print(std_dev)

[[-1.29741735 -0.95143939 -0.60546143 -0.25948347  0.08649449  0.43247245]
 [ 1.12442837  1.47040633 -0.95143939 -1.29741735  0.77845041  1.47040633]]
4.75
2.890357532670771


In [110]:
#Mathematical function
#Aggregation
arr=np.array([1,2,3,4,5,6,7,8])

print(np.min(arr))
print(np.max(arr))
print(np.sum(arr))
print(np.prod(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.mean(arr))
print(np.var(arr))
print(np.std(arr))


1
8
36
40320
0
7
4.5
5.25
2.29128784747792


In [115]:
#rounding
arr=np.array([1,2,-3,4,5,7,6,7,8])

print(np.round(3.14))
print(np.ceil(3.14))
print(np.floor(3.14))
print(np.trunc(3.14))

print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr))

3.0
4.0
3.0
3.0
[-3  1  2  4  5  6  7  8]
[-3  1  2  4  5  6  7  7  8]
[1 2 3 4 5 7 6 7 8]
